name: Deploy

on:
  pull_request:
    types:
      - closed

concurrency: deploy

jobs:
  apply:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: aws
    steps:
      - uses: actions/checkout@v4

      - name: Download Assets
        uses: dawidd6/action-download-artifact@v2
        with:
          name: build
          workflow: build.yml
          workflow_conclusion: success
          commit: ${{ github.event.pull_request.head.sha }}
          path: ./build

      - name: Cache Prod Node Modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-prod-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install production dependencies
        env:
          NODE_ENV: production
        run: |
          rm -rf node_modules
          npm ci

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --provenance --access public
