name: Tag

on:
  pull_request:
    types:
      - closed

concurrency: tag

jobs:
  createTag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Assets
        uses: dawidd6/action-download-artifact@v2
        with:
          name: build
          workflow: build.yml
          workflow_conclusion: success
          commit: ${{ github.event.pull_request.head.sha }}
          path: ./build

      - name: Cache Prod Node Modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-prod-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install production dependencies
        env:
          NODE_ENV: production
        run: |
          rm -rf node_modules
          npm ci

      - name: Tag
        run: |
          npm version patch

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: prod-build
          path: build
